name: SonarQube Code Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sonarqube:
    name: SonarQube C Analysis & Quality Gate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Linux Kernel Headers, Cppcheck & Security Analyzers
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential kmod linux-headers-generic cppcheck flawfinder python3

      - name: Install Sonar Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5
        with:
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}

      - name: Run Build Wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir bw-output make

      - name: Run Static Analysis & Generate Sonar Generic Issues Report
        run: |
          python3 scripts/generate_sonar_report.py

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.cfamily.build-wrapper-output=bw-output
            -Dsonar.externalIssuesReportPaths=sonar-issues.json

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
